### ISSUE TITLE
Would you please develop to support dulwich(a python port of Git)?

### ISSUE THREAD

**Issue by suliveevil** [ZSaberLv0/ZFVimGitUtil#1]
I'm using iVim on iPadOS, but couldn't use Git on iPadOS due to Apple's sandboxed App.

**Comment by ZSaberLv0** [comment]
dulwich seems funny, but as a small and simple toolbox, I don't think it is a good design to support it within this plugin, instead, I think it's better to supply dulwich's command line wrapper, for example: `/path/dulwich_git_wrap.py clone xxx`, and then let user able to customize the `git` executable of this plugin

since dulwich did not supply such command line tool for now, and there's already a related opening issue (https://github.com/dulwich/dulwich/issues/645), I won't reinvent the wheel

of course, please let me know when dulwich able to supply the command line tools, and I'll add this feature

PS: I'm also facing same issue with free version of `DroidVim` of Android :P dulwich seems a good workaround

**Comment by suliveevil** [comment]
😂 I will use sync tool instead of running Git with Vim.
